### PR TITLE
Dockerised the project and updated the README.md

### LINKED ISSUE #217: Dockerise the application to run the it locally
I can see in the comments and the issues section that a lot of users are facing issues while running the project locally.

I would like to contribute to this project by creating a docker compose file using which all the users will be able to run this project locally without having the headache of setting up everything from scratch.

If this feature request gets approved, I would love to work on it right away.

### PR DESCRIPTION
**Pull request by creatorshubham**
This PR is for the #217 issue

Fixes #217

### CODE REVIEW

**Comment by creatorshubham** [comment]
Hi @mohamedsamara , please have a look and let me know if anything else is required here.

**Comment by mohamedsamara** [comment]
Hey @creatorshubham! Thanks for the PR. I'll take a look soon. Looks good! I will test it on my machine.

**Comment by mohamedsamara** [comment]
Hey @creatorshubham! Were you able to see the app running in the browser when running docker compose up? I pulled the changes locally and ran the container but I wasn't able to see the app on browser. I think the app is not exposed outside the container.

**Comment by creatorshubham** [comment]
Hey @mohamedsamara , yes, I am able to access the app on the browser after running docker compose up. It is getting exposed on the 8080 port on your localhost. Please make sure that 8080 port is not already occupied by some other app or service.

If that port is free then the app will be accessible on localhost:8080

**Comment by creatorshubham** [comment]
Hi @mohamedsamara, did you get the chance to verify it on your local system?

**Comment by mohamedsamara** [comment]
@creatorshubham Thanks for the PR. Just merged the changes 👍

**Pull request merged**
